### ISSUE TITLE
Allowing setting a constant color for the temporary containers?

### ISSUE THREAD

**Issue by magpie514** [igorlogius/open-in-temp-container#5] opened 2023-10-30 03:55 UTC
Hello! Very useful extension, and gives even more love to containers.

Would it be possible to allow setting a specific color for all generated temporary containers? It'd be a nice way to separate from other non-temporary containers just looking at the tab bar. (for example none of my ID containers use red, so if I set the temporary ones to red, I know it's the temporary one at a glance).

**Comment by igorlogius** [comment] 2023-10-30 08:11
yeah, that is doable. - Just please be aware that the colors  can not be freely choosen but are limited to the following set

    "blue"
    "turquoise"
    "green"
    "yellow"
    "orange"
    "red"
    "pink"
    "purple"
    "toolbar"

ref. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities/create


I'll try and look into adding an option so you can set a fixed color.

**Comment by igorlogius** [comment] 2023-10-30 10:18
Sidenote: This "mode" will likely confuse users which are already used to the colors indicating different cookieStores.

**Comment by igorlogius** [comment] 2023-10-30 10:54
The issue should be addressed in `1.1.6`.

@magpie514 This issue is now assigned to you to double check.

If you think the issue is resolved you can just close the issue but 
if you  think the issue still needs attention, just write another comment with what you think is missing or not working and i'll take another look into it.

**Comment by magpie514** [comment] 2023-10-30 12:43
Thank you for the quick response and implementation!
I'll close the issue since it's exactly what I asked for, and works as expected. Now I can tell at a glance which tab is temporary. 
Thanks again!

**Comment by anewuser** [comment] 2023-11-04 20:21
I only use two permanent containers and was actually going to request the opposite: a way to **exclude** specific colors. 

Since there are only eight available color options (plus `toolbar`), what about listing them along with checkboxes?

**Comment by igorlogius** [comment] 2023-11-04 20:39
@anewuser sure. i dont see why not.

**Comment by igorlogius** [comment] 2023-11-04 21:46
@anewuser 

https://github.com/igorlogius/open-in-temp-container/assets/67047467/56918c9e-faaa-4131-b141-2fd4d8d22575

Hope it helps.

**Closed** 2023-11-04 21:47 UTC
Labels: 💡 Feature Request, 🥳 Done/Delivered/Fixed

**Comment by anewuser** [comment] 2023-11-04 23:54
Thank you for implementing all these features so fast!
