### ISSUE TITLE
Auto Temp Container Mode skips `Secure Site Not Available` page when browser is in HTTPS-Only mode

### ISSUE THREAD

**Issue by ivysrono** [igorlogius/open-in-temp-container#12] opened 2024-03-10 03:23 UTC
**Describe the bug**
[HTTPS-Only Mode in Firefox | Firefox Help](https://support.mozilla.org/en-US/kb/https-only-prefs#w_secure-site-not-available)

`Secure Site Not Available` page and `Continue to HTTP Site` button only show when you visit from http://* , without when you visit direct from https://* , however OpenInTempContainer re-open the new site in new temp tab directly with https.

I have try to add `^http:\/\/*` to rules but useless. The only way is open blank temp tab first then copy the http url to the tab.

**Comment by igorlogius** [comment] 2024-03-10 09:30
Looks like https-only mode manipulates the request earlier then any addon can, which explains why the regex exception list doesn't work. Sadly i dont see a way to work around this at the moemnt. You should still be able to just use the https-only exception list 

![Screenshot_2024-03-10_10-28-59](https://github.com/igorlogius/open-in-temp-container/assets/67047467/22f4d199-db86-4726-b9de-fd0de72eca9c)

Hope that helps a bit.

**Comment by igorlogius** [comment] 2024-03-10 10:22
After doing a little testing ... i have to correct my previous statement ... and say ... that i can just not reproduce this bug.

The Site you mentions appears for me, as long as i did not add it to the temporary exceptions list at least, even with Auto Mode enabled. 


https://github.com/igorlogius/open-in-temp-container/assets/67047467/30f61959-6830-484e-b837-7f4f9acadd0d




Please provide a screen recording of your issue , otherwise i have to reject and close this ticket.

**Comment by igorlogius** [comment] 2024-03-10 13:31
> I have no time today and tomorrow, please wait 72 hours.

noted. i'll wait.

**Comment by igorlogius** [comment] 2024-03-12 09:31
>reback to http:// by server side, so you don't find this issue.

Not sure if i understand you correctly. Could you ellaborate what you think the difference between `http.badssl.com` and the other sites is? 

> http://www.xuanxuango.com/

Here i get a `The connection has timed out`
 
> http://www.zeuux.com/

And here i get `Unable to connect`

Either i am somehow region restricted or these sites are misconfigured in some way, but i am not 100% sure.

**Comment by igorlogius** [comment] 2024-03-12 10:15
https://github.com/igorlogius/open-in-temp-container/assets/67047467/33904d86-a111-4d38-967e-1b83df7e69bf

**Comment by igorlogius** [comment] 2024-03-12 10:17
Should be fixed in `1.1.20`

**Closed** 2024-03-12 11:13 UTC
Labels: bug, 🥳 Done/Delivered/Fixed
